spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: iam_user
    password: iam_pass
  jpa:
    show-sql: true
  flyway:
    enabled: false

logging:
  level:
    com.cmtdevsolutions.iam: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE